### ISSUE TITLE
The gateway, addons, and third party services - Privacy

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/addon-list#1299]
Every time I start the Zigbee2MQTT adapter, I see these messages in the log:

```
2021-02-11 15:09:02.961 INFO   : zigbee2mqtt-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/schema.json because it has no messageType
2021-02-11 15:09:04.031 INFO   : zigbee2mqtt-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/messages/definitions.json because it has no messageType
```

I understand that from a technical/funcional standpoint these are nothing to worry about.

But from a privacy perspective I'd like to know: is the gateway actually firing off a message to a Github server every time I launch this addon?

Does it do this for all addons?

Even just a 'ping' to a Github server means that the Gateway is sending my IP address to Microsoft. On its own, Microsoft could use this to record activity patterns, and derive new insights from there by comparing me to other people. 

If Microsoft connects the IP address to other information about me (which a Github or Microsoft account would swiftly allow for), then the IP address could legally be classified as personal data.

I am aware that some of my own addons connect to third party servers. 
- Internet radio connects to radio stations
- Zigbee2MQTT connects to Github, and to various firmware update servers
- Candle Manager connects to Github and Arduino

This raises a bigger question, namely: currently when addons are installed users are not presented with any information detailing what data may be collected, or which servers may be connected to. Users may not consent to this. Legally, some of these connections could be classified as using the `Legitimate interest` legal ground (e.g. the internet radio addon). But then the GDPR still has a lot of requirements surrounding informing users that the current situation is unlikly to cover properly.

As a side note, if a user installs the Gateway and chooses to skip the tunneling setup step, then I believe they are currently never presented with any need to accept a privacy policy.

**Comment by benfrancis** [comment]
> But from a privacy perspective I'd like to know: is the gateway actually firing off a message to a Github server every time I launch this addon? Does it do this for all addons?

Not that I'm aware of, though @mrstegeman might correct me. I think this is just referring to the schema URI as an identifier for the schema, rather than indicating that a resource is being fetched. In the same way that all W3C Thing Descriptions contain the context URI https://www.w3.org/2019/wot/td/v1.

> This raises a bigger question, namely: currently when addons are installed users are not presented with any information detailing what data may be collected, or which servers may be connected to.

Nice can of worms you have there :)

To the best of my knowledge none of the WebThingsIO (previously Mozilla IoT) authored add-ons share private user data with any online services (though I didn't personally write or code review all of the add-ons myself, so please let me know if you find anything like that).

For third party add-ons my assumption would be that it is the responsibility of the developer to disclose any data collection and ensure the necessary consent has been provided by the user for that to happen. There is currently no built-in mechanism to help developers do that. The closest we have is the `homepage_url` and `license_url,` either of which could include a link to a privacy policy.

A step forward here could be to add a privacy policy field to the add-on manifest alongside the license field and surface this in the UI, so that users can review the privacy policy before installing the add-on. Then clicking the install button would provide a certain level of consent, but you may want to satisfy yourself as to whether that is sufficient to comply with laws in any particular country (e.g. GDPR). I've filed https://github.com/WebThingsIO/gateway/issues/2783 for the front end part of that. [1]

> As a side note, if a user installs the Gateway and chooses to skip the tunneling setup step, then I believe they are currently never presented with any need to accept a privacy policy.

That's correct. The privacy policy is for the registration server of the tunneling service, because it collects email addresses to associate with domains. If you don't sign up to that service you don't need to agree to its privacy policy.

Footnotes:
1. Note that as we continue down this road, at some point I expect we're going to need to develop the current set of [guidelines](https://github.com/WebThingsIO/addon-list/blob/master/guidelines.md#guidelines) into a more formal add-ons policy like [the one Mozilla has for Firefox](https://extensionworkshop.com/documentation/publish/add-on-policies/). If you know the history of Firefox add-ons and follow that through to its natural conclusion then we're likely to end up having to introduce more restrictions on what add-ons can and can't do. Probably eventually ending up with an explicit add-ons API, rather the current liberal execute any code you like approach! Then we will also eventually have the problem of backwards compatibility whenever the API changes. We've always known we'd probably eventually have to do that, but we wanted to give developers the freedom to explore the kinds of things add-ons might need to do, before locking them down to a fixed API. So in other words, you raise a very important point, but be careful what you wish for!

**Comment by mrstegeman** [comment]
> Every time I start the Zigbee2MQTT adapter, I see these messages in the log:
> 
> ```
> 2021-02-11 15:09:02.961 INFO   : zigbee2mqtt-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/schema.json because it has no messageType
> 2021-02-11 15:09:04.031 INFO   : zigbee2mqtt-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/messages/definitions.json because it has no messageType
> ```

The strings come directly from here:
* https://github.com/WebThingsIO/gateway-addon-ipc-schema/blob/master/schema.json#L3
* https://github.com/WebThingsIO/gateway-addon-ipc-schema/blob/master/messages/definitions.json#L3

**Comment by flatsiedatsie** [comment]
@mrstegeman Thanks.

@benfrancis The privacy improvements I suggested aren't so much a personal wish, as they are a legal reality WebThings will have to deal with at some point. If I hadn't brought it up, someone else eventually would have. Don't shoot the messenger :-)

> locking them down to a fixed API

I'm not sure I'd describe the current situation as a `liberal execute any code you like` situation( not being able to use `apt-get` is quite a challenge), but I understand it could be limited more. I'd love to learn more about what you foresee here, and why you believe that the Firefox addons situation is a meaningful template/roadmap for a smart home platform.

**Comment by benfrancis** [comment]
> The privacy improvements I suggested aren't so much a personal wish, as they are a legal reality WebThings will have to deal with at some point. 

Of course I agree that WebThings must comply with (and ideally go beyond) the law in order to protect privacy, and I think you're right to highlight areas that might currently not be the case, thank you.

Having the ability for users to agree to a privacy policy is one component, but how can users be sure that an add-on is doing what it says it is doing? Especially when add-ons have free reign to execute arbitrary code. The current solution to that problem is code review of add-ons before adding them to the directory, but that isn't a solution which scales very well.

> I'm not sure I'd describe the current situation as a liberal execute any code you like situation( not being able to use apt-get is quite a challenge)

I think it's likely that future gateway software images may not even have apt installed, it already isn't on many platforms on which the gateway application runs. It's a challenge for everyone because another add-on making a change to system-wide packages could prevent your add-on from working.

> I'd love to learn more about what you foresee here, and why you believe that the Firefox addons situation is a meaningful template/roadmap for a smart home platform.

Not just Firefox, any add-on/app platform has the same issues. Firefox add-ons used to allow users to do basically anything with chrome privileges, before it had to be locked down to the [Web Extensions API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) in order to protect privacy and security (and reliability). SmartThings followed a similar path, starting out with a very liberal policy allowing custom device handlers written in Groovy, but eventually [banning those](https://staceyoniot.com/smartthings-will-kill-legacy-features-to-make-a-smarter-home/) in favour of a fixed API, in the interests of security.

I'm really straying off topic here from what was a fairly simple suggestion (sorry), but while you raise the issue of trusting add-ons, I just wanted to highlight that tighter privacy/security restrictions and hackability (which I know you also care about) are often at odds with each other.

**Comment by tim-hellhake** [comment]
> But from a privacy perspective I'd like to know: is the gateway actually firing off a message to a Github server every time I launch this addon?

No, that's just the id of the schema.
